[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "gcpri"
version = "0.1.0"
description = "GCP Resource Inventory"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "google-cloud-asset",
    "pandas",
]
